# Generated by Django 5.1.6 on 2025-03-06 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feligreses', '0002_iglesia_feligres_iglesia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iglesia',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='feligres',
            name='iglesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feligreses.iglesia'),
        ),
        migrations.AlterField(
            model_name='iglesia',
            name='ciudad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='iglesia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
