# Generated by Django 5.1.6 on 2025-04-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feligreses', '0003_remove_iglesia_telefono_alter_feligres_iglesia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feligres',
            name='iglesia',
        ),
        migrations.RenameField(
            model_name='feligres',
            old_name='nombre',
            new_name='apellido_paterno',
        ),
        migrations.RenameField(
            model_name='feligres',
            old_name='cargo',
            new_name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='feligres',
            name='antecedentes',
        ),
        migrations.RemoveField(
            model_name='feligres',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='feligres',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='feligres',
            name='telefono',
        ),
        migrations.AddField(
            model_name='feligres',
            name='afinidad_contacto_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='afinidad_contacto_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='anio_cursado_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='anio_cursado_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='anio_cursado_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='anio_cursado_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='bautismo_anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='bautismo_dia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='bautismo_lugar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='bautismo_mes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='celular',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='ciudad_nacimiento',
            field=models.CharField(default='Sin registro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feligres',
            name='ciudad_residencia',
            field=models.CharField(default='Sin registro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feligres',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='departamento_nacimiento',
            field=models.CharField(default='Sin registro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feligres',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_feligreses/'),
        ),
        migrations.AddField(
            model_name='feligres',
            name='hijo_1_edad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='hijo_1_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='hijo_2_edad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='hijo_2_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='hijo_3_edad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='hijo_3_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='hijo_4_edad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='hijo_4_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='hijo_5_edad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='hijo_5_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='hijo_6_edad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='hijo_6_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='huella',
            field=models.ImageField(blank=True, null=True, upload_to='huellas_feligreses/'),
        ),
        migrations.AddField(
            model_name='feligres',
            name='matrimonio_civil_anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='matrimonio_civil_dia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='matrimonio_civil_lugar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='matrimonio_civil_mes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='matrimonio_eclesiastico_anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='matrimonio_eclesiastico_dia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='matrimonio_eclesiastico_lugar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='matrimonio_eclesiastico_mes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='nombre_apellidos_conyuge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='nombre_contacto_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='nombre_contacto_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='nombres',
            field=models.CharField(default='Sin registro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feligres',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='pais',
            field=models.CharField(default='Sin registro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feligres',
            name='primaria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='secundaria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='telefono_contacto_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='telefono_contacto_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='tipo_sangre',
            field=models.CharField(default='Sin registro', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feligres',
            name='titulo_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='titulo_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='titulo_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='titulo_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feligres',
            name='universitaria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feligres',
            name='cedula',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Iglesia',
        ),
    ]
