# Generated by Django 5.1.6 on 2025-04-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feligreses', '0005_rename_apellido_paterno_feligres_apellidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feligres',
            name='departamento_nacimiento',
        ),
    ]
