# Generated by Django 5.1.6 on 2025-04-03 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feligreses', '0006_remove_feligres_departamento_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feligres',
            old_name='ciudad_nacimiento',
            new_name='departamento_nacimiento',
        ),
    ]
