# Generated by Django 5.1.6 on 2025-04-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feligreses', '0007_rename_ciudad_nacimiento_feligres_departamento_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='feligres',
            name='cargo_eclesiastico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
